*** 두부조림 (Braised Tofu)

This is the simplest version that I came up with. It's enough to feed
5-6 adults as the main banchan.

*ingredients*
- 2 packages of extra firm tofu
- 5 cloves of garlic chopped
- 3 green onions sliced ~1cm length
- 4 cm knob of ginger chopped
- 1/2 cup soy sauce
- 2-3 tablespoon sesame oil
- water

*steps*

1. Cut the tofu into 1 in x 2 in x 2 in (2 cm x 5cm x 5cm) squares.
2. (optional) Remove the water from tofu. You can put a paper
   towel/thin towel on a dish, layer the tofu slices above the paper
   towel/thin towel, and put another dish + heavy things on the
   top. Leave it for a few hours and pat the tofu dry with the paper
   towel/thin towel.
3. (optional) If you dried the tofu, pan fry it. Heat some oil on a
   wide pan, and pay fry the tofu slices until it browns a little (you
   can brown it a tiny bit, but if you properly fry it, it will look
   like [this](https://www.maangchi.com/wp-content/uploads/2016/02/fried-tofu-590x370.jpg).
4. Add the tofu to a wide pan. Dump the garlic/ginger/onion and soy
   sauce. Braise until the tofu is flavored (about 20 minutes), adding
   water if needed. If the sauce doesn't fully cover the tofu, flip them
   occasionally.
5. Drizzle some sesame oil at the end.

-------------------------------------------
*notes*
- If you do steps 2 and 3, you'll end up with chewier, firmer tofu. If
  you don't, it's a lot softer and crumblier, which is often how I
  have it at home! It's really easy to make if you skip the removing
  water/pan frying step, but it will be harder to serve because
  they'll break easier.
- You can obviously add more ginger/garlic if you want!
- If you like it spicy, add a few tablespoons of Korean chili flakes
  and/or fresh spicy chilis. You can also replace the soy sauce with
  Korean chili paste (depends on your tolerance/taste. When it's spicy
  enough, add soy sauce to taste, and water to braise).
- While braising, add a couple 5 cm squares of dried kelp (dashima in Korean or
  kombu in Japanese) to add extra umami.
- For non vegetarian version and even extra umami, add a couple some
  dried small fish (sardine is usually the common option in Korea)
  while braising.
