*** 배추김치 (cabbage kimchi)

*재료*
- 양념
  - 고추가루 1 컵
  - 액젓 1/2 컵
  - 새우젓 1/4 컵
  - 마늘 1/4 컵
  - 생강 2 Tbsp
  - 설탕 1 Tbsp (사과/배 쓰면 생략 가능)
  - 어슷 썬 파 1 묶음

- 소금 1 컵 (절임용)

- 배추 2.25kg / 5lbs (작은거 약 2포기)
- 무 작은거 (지름 15 cm / 6 inch; 길이 20 cm / 8 inch) 1 개
- 배 또는 사과 1-2 개. 양념과 섞을거면 대강 썰어놓고, 아니면 두껍게 썰어놓는다.
- 미나리 1 단 (생략 가)

*방법*
1. 반나절전에 배추를 절인다. 배추를 반으로 쪼개 소금 1컵 에 절인다. 귀찮으면 먹기 좋게 썰은 후에 절여도 좋다. 맛을 봐서 짭짤할때까지 절인다.
2. 고추가루, 액젓, 새우젓, 마늘, 설탕을 섞어 놓는다. 섞어야 고추가루가 풀어진다. 너무 되면 걸쭉해질때까지 물을 넣는다.
3. 무를 썰어놓는다. 어슷 썰거나 단무지 모양으로 썰어도 좋다. 약 30분간 절인다.
4. 양념, 무, 파를 모두 섞는다.
5. 절여놓은 배추를 헹구고, 섞어놓은 양념을 배추에 넣는다. 배추를 이미 썰어놨으면 양념, 무, 파, 배추를 다 섞으면 된다.
6. 통에 차곡차곡 넣는다. 배추가 거의 잠길정도로 소금물을 타서 부어준다.
7. 뚜껑을 살짝 닫고 밤새 밖에 둔다. 여름이면 잠깐만 놔둬도 된다.
8. 뚜껑을 닫고 김치를 냉장고로 옮긴다.

-------------------------------------------
*ingredients*
- stuffing
  - 1 cup chili flakes
  - 1/2 cup fish sauce
  - 1/4 cup salted shrimp
  - 1/4 cup minced garlic
  - 2 Tbsp minced ginger
  - 1 Tbsp sugar (can skip if using grated pear or apple)
  - 1 bunch of green onion (in 2-inch slices)

- 5 lbs / 2.25 kg napa cabbage (about 2 small ones)
- peeled daikon (6 inch / 15 cm diameter; 8 inch / 20 cm length)
  Korean daikon preferred because it tends to be sweeter. (about 1
  small Korean daikon, or a few daikons. TODO get the weight next
  time) (cut into 2 inch match sticks, or 1/2 inch thick half/quarter
  moons if you want pieces of it)
- 1-2 Asian pear or apple (grated if mixing with the stuffing, or sliced into thick match sticks
  or 1/2-inch slices if you want pieces of it)
- Optional: 1 bunch of minari (미나리 Korean) / seri (セリ Japanese)

- 1 cup + 2 Tbsp sea salt (Iodized salt can add bitterness.)


1. Remove the big green leaves from the cabbages. You can use the
   green leaves for soup or salad, but they're too tough for
   kimchi. Cut the cabbage in half, and add the salt between the
   leaves, with extra on the thicker white parts of the leaves.
   When you fold the thick white part of the leaf and it doesn't break,
   it's ready. It takes about 6 hours to salt the cabbages. If
   you're in a hurry, you can add more salt to salt them more
   quickly. When you taste it, it should be deliciously salty, like
   potato chips. If it's too salty, soak them in plain water until
   it's perfectly salty. When the cabbages are ready, rinse, and
   drain/squeeze them well.
2. Mix the ingredients for the stuffing. Instead of mincing garlic and
   ginger, You can blend all of the ingredients if you're feeling
   lazy. If using the pears/apples instead of sugar, add them to the
   stuffing mixture. As the chili flakes rehydrate, the mixture will
   get dry. Add some water until the texture resembles that of oatmeal.
3. Add 2 Tbsp salt to the daikons and after 30 minutes rinse and
   drain. Daikon will get salted more quickly than cabbage. Like with
   the cabbage, if it's too salty, soak in water until they're ready.
4. Mix the stuffing, the daikon, and the apple/pear (if using slices of them).
5. Stuff the cabbages with the stuffing.
6. Put kimchi in a container with a lid. Try to cover the cabbage and
   daikon with the sauce. If you can't, pour in some salt water (about
   ocean water saltiness) just enough to cover the kimchi.
7. Let it sit in room temperature overnight (or less depending on how
   quickly you want to ferment) with the lid loosely closed.
8. Tigthen the lid, and move it to the fridge. Make sure the kimchi is
   submerged, especially after taking some out.
-------------------------------------------
*notes*
- If you chop the cabbages into bite-size pieces before salting them, it's a
  lot easier to make and eat though less pretty. If you chop them first, you can
  separate the leafy part from the stalky part so you can add a little
  more salt to the stalky parts. Replace steps 4 and 5 with "mix
  everything".
- Instead of adding salt water at the end, you can add some cooled salty kelp broth for extra umami.
- For making vegan kimchi, you can replace fish sauce and salted shrimp with soy sauce (but I've never tried!).
- I tried using 2/3 cup chili flakes, and adding more water so the
  stuffing is runnier and less spicy. This made it taste more like my
  mom's. Still a lot spicier than my grandma's, so maybe she used very
  little chili flakes?
