*** 간장 새우장 Soy Sauce Marinated Shrimp

*재료*
- 양념
  - 간장 3컵
  - 사케/맛술 1컵
  - 물 2컵
  - 마늘 5-7 쪽
  - 생강 5 센치 저민거
  - 풋고추 5개
  - 홍고추 1개
  - 할라페뇨/매운 고추 1개
  - 유자주스 2스푼
  - 양파 작은거 한개

- 새우 900 그람 (냉동 쓰면 찬물에 해동할 것)

*방법*
1. 양념을 모두 섞고 부글부글 끓기 시작하면 불을 끄고 식혀둔다.
2. 새우는 깨끗이 씻고, 앞다리, 머리/등에 있는 뾰족한 부분, 꼬리에 붙은 뾰족한 부분을 잘라낸다. 등에 있는 내장을 이쑤시개로 꼬리쪽에 있는 껍질쪽에서 뽑아낸다.
3. 유리통에 새우를 깔고 양념을 붓는다. 새우가 잠기도록 조심한다.
4. 둘쨋날에 양념을 냄비에 따라 부어 부글부글 끓인 후, 식혀서 다시 부어준다.
5. 셋쨋날에 한번 더 끓여준다.
6. 넷쨋날부터는 먹을 수 있다. 나중에 먹을거면 매일 양념을 끓이고 식힌후에 부어준다.

-------------------------------------------
*ingredients*
- brine
  - 3 cup soy sauce
  - 1 cup sake/cooking wine
  - 2 cup water
  - 5-7 cloves of garlic. pressed.
  - 2 in. ginger. sliced.
  - 5 Korean green chilis (not spicy). thickly sliced.
  - 1 red chili (slightly spicy). thickly sliced.
  - 1 jalapeno. sliced.
  - 2 Tbsp yuzu/lemon juice
  - 1 small onion. cut in halves.

- 2 lbs shrimp (if using frozen shrimp, defrost it in cold water)

*directions*
1. Put the brine ingredients in a pot. Bring it to a rolling boil. Turn off the heat and set it aside to cool.
2. Clean the shrimps. Cut off the legs, and the pointy parts in the upper back and in the tail. Pull out the gut using a toothpick from near the tail. Rinse well.
3. Put the cleaned shrimps in a glass container, and pour the brine over it. Make sure that the shrimps are submerged.
4. On the second day, pour out just the brine into a pot and repeat the step 1. Pour it back into the container once it's cooled.
5. On the third day, pour out just the brine into a pot and repeat the step 1. Pour it back into the container once it's cooled.
6. On the fourth day, you can eat the shrimp. It should keep for a week. Every day, make sure to boil the brine and put it back once it's cooled.

----------------------------------------
*notes*
- You'll end up with a lot of brine! Reduce it and use it instead of salt or soy sauce when cooking.
- This dish is traditionally made with raw crabs, but recently people started using shrimp because it's easier to find, and also easier to prepare.
- When serving, add some of the brine over the shrimp. The brine is really good with plain rice. This is especially good with rice and seaweed (nori). Add some radish sprouts or thinly sliced cucumber and make it a wrap.
- The head of the shrimp has what's equivalent to tomalley in crab or lobster.
